server:
  port: 8089
spring:
  application:
    name: UserinfoApplication
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: huang19568
    url: jdbc:mysql://127.0.0.1:3306/can301?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  cloud:
    nacos:
      config:
        username: nacos
        password: Huang19568
      discovery:
        enabled: true
        service: userinfo
        server-addr: 127.0.0.1:8848

#dubbo:
##  application:
##    name: userinfo
#  protocol:
#    name: dubbo
#    port: 20880
#  registry:
#    address: nacos://127.0.0.1:8848
#  scan:
#    base-packages: com.example.userinfo.repository
#  consumer:
#    timeout: 4000
#  provider:
#    version: 1.0.0

