server:
  port: 8087
spring:
  application:
    name: PostinfoApplication
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: huang19568
    url: jdbc:mysql://127.0.0.1:3306/can301?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  cloud:
    nacos:
      config:
        username: nacos
        password: Huang19568
      discovery:
        enabled: true
        service: postinfo
        server-addr: 127.0.0.1:8848